geekshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path
from basketapp.views import basket_add, basket_remove, basket, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name="index"),
    path('contacts/', contacts, name="contacts"),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/basketapp/models.py
from django.db import models

from geekshop import settings
from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='basket',
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество',
        default=0,
    )
    add_datetime = models.DateTimeField(
        verbose_name='время',
        auto_now_add=True,
    )

    is_deleted = models.BooleanField(default=False)

    @property
    def product_cost(self):
        return self.product.price * self.quantity

    @property
    def total_quantity(self):
        _items = Basket.objects.filter(user=self.user)
        _totel_quantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totel_quantity

    @property
    def total_cost(self):
        _items = Basket.objects.filter(user=self.user)
        _totel_cost = sum(list(map(lambda x: x.product_cost, _items)))
        return _totel_cost

geekshop/basketapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from basketapp.models import Basket
from mainapp.models import Product

from django.contrib.auth.decorators import login_required

from django.template.loader import render_to_string
from django.http import JsonResponse


@login_required
def basket(request):
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user).order_by('product__category')
        context = {
            'basket': basket
        }
        return render(request, 'basketapp/basket.html', context)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:product', args=[pk]))

    product = get_object_or_404(Product, pk=pk)

    basket = Basket.objects.filter(user=request.user, product=product).first()

    if not basket:
        basket = Basket(user=request.user, product=product)

    basket.quantity += 1
    basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, pk, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        new_basket_item = Basket.objects.get(pk=int(pk))

        if quantity > 0:
            new_basket_item.quantity = quantity
            new_basket_item.save()
        else:
            new_basket_item.delete()

        basket = Basket.objects.filter(user=request.user). \
            order_by('product__category')

        context = {
            'basket': basket,
        }

        result = render_to_string('basketapp/includes/inc_basket_list.html', context)

        return JsonResponse({'result': result})

geekshop/basketapp/templates/basketapp/basket.html
{% extends 'geekshop/base.html' %}
{% load static %}


{% block js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="container">
            <div class="row basket_list">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">№</th>
                  <th scope="col">Продукт</th>
                  <th scope="col">Количество</th>
                  <th scope="col">Стоимость</th>
                  <th scope="col">Итого</th>
                  <th scope="col">Удалить</th>
                </tr>
              </thead>
              <tbody>
              {% for item in basket %}
                  <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td>{{ item.product }}</td>
                      <td>
                          <input type="number" name="{{ item.pk }}"
                          min="0"
                          value="{{ item.quantity }}">
                      </td>
                      <td>{{ item.product.price }}</td>
                      <td>{{ item.product_cost }}</td>
                      <td>
                          <button class="btn btn-round">
                              <a href="{% url 'basket:remove' item.pk %}" class="">
                                  удалить
                              </a>
                          </button>
                      </td>
                  </tr>
              {% endfor %}

              </tbody>
            </table>

             {% if basket %}
                <div class="basket_summary">
                    В корзине
                     {{ basket.0.total_quantity }} товаров общей стоимостью
                     {{ basket.0.total_cost }} руб.
                </div>
              {% endif %}

            </div>
        </div>
    {% endif %}
{% endblock %}