geekshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path
from basketapp.views import basket_add, basket_remove, basket, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name="index"),
    path('contacts/', contacts, name="contacts"),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>/', product, name='product'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name or f"Category with id - {self.pk}"

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория',
    )
    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )
    image = models.ImageField(
        upload_to='product_images',
        blank=True,
        verbose_name='изображение',
    )
    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=100,
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество товара на складе',
        default=0,
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name or f"Product with id - {self.pk}"

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

geekshop/mainapp/views.py
import random

from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import ProductCategory, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)

    return same_products


def products(request, pk=None, page=1):
    title = 'продукты/каталог'
    basket = get_basket(request.user)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    links_menu = ProductCategory.objects.all()
    products = Product.objects.all().order_by('price')

    if pk is not None:
        if pk == 0:
            products = Product.objects.filter(is_deleted=False).order_by('price')
            category = {'pk': 0, 'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(is_deleted=False, category__pk=pk).order_by('price')

        paginator = Paginator(products, 2)

        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)


        context = {
            'title': title,
            'links_menu': links_menu,
            'hot_product': hot_product,
            'same_products': same_products,
            'products': products_paginator,
            'category': category,
        }
        return render(request=request, template_name='mainapp/products.html', context=context)


    context = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'products': products,
        'basket': basket,
    }

    return render(request=request, template_name='mainapp/products.html', context=context)


def product(request, pk):
    title = 'продукты'

    context = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', context)

geekshop/mainapp/templates/mainapp/product.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
{% endblock %}

{% block content %}
	<div class="details">
        {% include 'mainapp/includes/inc_category_menu.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product text-center">
                    <img src="/media/{{product.image}}">
                </div>
                <div class="slider-control d-flex">
                    <div class="block">
                        <a href="#"><img src="/media/{{product.image}}" alt="" class="w-100">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{product.image}}" alt="" class="w-100">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{product.image}}" alt="" class="w-100">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price">{{ product.price }}<span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ product.description }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
{% endblock %}

{% block content %}
		<div class="details">
			{% include 'mainapp/includes/inc_category_menu.html' %}

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product text-center">
						<img src="/media/{{hot_product.image}}">
					</div>
					<div class="slider-control d-flex">
						<div class="block">
							<a href="#"><img src="/media/{{hot_product.image}}" alt="" class="w-100">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/media/{{hot_product.image}}" alt="" class="w-100">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/media/{{hot_product.image}}" alt="" class="w-100">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">{{ hot_product.name }}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price">{{ hot_product.price }}<span>руб</span></p>
					<a href="{% url 'products:product' hot_product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						{{ hot_product.description }}
					</div>
				</div>
			</div>

		{% if products %}
		<div class="featured mt-5">
			{% if category %}
				<h2>
					Категория: {{ category.name|title }}
				</h2>
			{% endif %}

			<div class="paginator">
			  {% if products.has_previous %}
				<a href="{% url 'products:page' category.pk products.previous_page_number %}">
				  <
				</a>
			  {% endif %}
			  <span class="current">
				страница {{ products.number }} из
				{{ products.paginator.num_pages }}
			  </span>
			  {% if products.has_next %}
				<a href="{% url 'products:page' category.pk products.next_page_number %}">
				  >
				</a>
			  {% endif %}
			</div>

			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% for product in products %}
					<div class="block">
						<a href="{% url 'products:product' hot_product.pk %}"><img src="/media/{{product.image}}" alt="">
							<div class="text">
								<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
								<h4>{{product.name}}</h4>
								<p>{{product.short_desc}}. </p>
							</div>
						</a>
					</div>
				{% endfor %}
				</div>
			</div>


			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="/static/geekshop/img/arrow.png" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="/media/{{product.image}}" alt="">
							<div class="text">
								<img src="img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					{% for prod in same_products %}
					<div class="block">
						<a href="#"><img src="/media/{{prod.image}}" alt="">
							<div class="text">
								<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
								<h4>{{prod.name}}</h4>
								<p>{{prod.short_desc}}. </p>
							</div>
						</a>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
		{% else %}

		{% endif %}
{% endblock %}